### ISSUE TITLE
[Bug]: Cannot Install 0.1.1 and 0.1.2

### ISSUE THREAD

**Issue by apoapostolov** [arcanistzed/zap#1]
### Expected Behavior

The mod installs

### Current Behavior

![image](https://user-images.githubusercontent.com/4083812/209786774-94758bb7-f789-4337-b6db-94f456f9fce1.png)

### Steps to Reproduce

1. Attempt to install the mod

### Version

0.1.2

### Foundry VTT Version

10 291

### Operating System

Windows

### Browser / App

Native Electron App

### Game System

No system

### Modules Disabled

- [X] I can confirm that disabling all of my other modules doesn't fix this issue.

**Comment by arcanistzed** [comment]
Thank you. The file wasn't included in the CI build 🤦
It should be fixed now

**Comment by apoapostolov** [comment]
All good now. Thanks!
